# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "nextflix"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[observability]
enabled = true

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
[placement]
mode = "smart"

# Environment Variables
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
[vars]
NODE_VERSION = ">=21.1.0"

[[d1_databases]]
binding = "DB"
database_name = "prod-d1-nextflix"
database_id = "5c5f2e57-1235-48e6-941e-54233268601d"
